version: '3.7'

volumes:
  cache:
  log:
  database:

networks:
  backend:
    name: fil_rouge_back

services:
  php:
    container_name: fil-rouge-app
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
    env_file:
      - ./docker/env/.env.php
    volumes:
      - .:/var/www/html
      - /var/www/html/database
      # does not work as intended
      - ./config/vhost.conf:/etc/apache2/sites-available/000-default.conf
      # does not work as intended
      - cache:/var/www/html/var/cache
      - log:/var/www/html/var/log
    ports:
      - '8001:80'
    networks:
      - backend

  mysql:
    container_name: fil-rouge-mysql
    image: mysql:5.7
    restart: on-failure
#    docker container exec -i fil-rouge-mysql bash -c 'exec mysql -uroot -prootroot' < ./database/DB.sql
    env_file:
      - ./docker/env/.env.mysql
    volumes:
      - database:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - backend
    depends_on:
      - php
